source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!

target 'VEAPISample' do
  pod 'YPImagePicker'
  pod 'VEPlaybackSDK', '1.26.0'
  pod 'VEEffectsSDK', '1.26.0'
  pod 'VideoEditor', '1.26.0'
  pod 'BanubaLicenseServicingSDK', '1.26.0'
  pod 'BanubaEffectPlayer', '1.26.0'
  pod 'BanubaSDK', '1.26.0'
  pod 'BanubaSDKServicing', '1.26.0'
  pod 'BanubaUtilities', '1.26.0'
  pod 'VEExportSDK', '1.26.0'

  pod 'BNBLicenseUtils', '1.24.1'
end
