source 'https://github.com/Banuba/specs.git'
source 'https://github.com/sdk-banuba/banuba-sdk-podspecs.git'

platform :ios, '15.0'
use_frameworks!

banuba_sdk_version = '1.43.0'

target 'VEAPISample' do

  pod 'BanubaVideoEditorCore', banuba_sdk_version

  pod 'BanubaSDK', banuba_sdk_version #in case of Banuba Face AR using

  pod 'YPImagePicker', :git => 'https://github.com/Yummypets/YPImagePicker.git', :branch => 'master'

end
